-- CreateTable
CREATE TABLE "pm25datas" (
    "id" SERIAL NOT NULL,
    "pm25_1" TEXT,
    "pm25_2" TEXT,
    "pm25_3" TEXT,
    "pm25_4" TEXT,
    "pm25_5" TEXT,
    "pm25_6" TEXT,
    "pm25_7" TEXT,
    "pm25_8" TEXT,
    "pm25_9" TEXT,
    "pm25_10" TEXT,
    "pm25_11" TEXT,
    "pm25_12" TEXT,
    "pm25_13" TEXT,
    "pm25_14" TEXT,
    "pm25_15" TEXT,
    "pm25_16" TEXT,
    "pm25_17" TEXT,
    "pm25_18" TEXT,
    "pm25_19" TEXT,
    "pm25_20" TEXT,
    "pm25_21" TEXT,
    "pm25_22" TEXT,
    "pm25_23" TEXT,
    "pm25_24" TEXT,
    "pm25_25" TEXT,
    "pm25_26" TEXT,
    "pm25_27" TEXT,
    "pm25_28" TEXT,
    "pm25_29" TEXT,
    "pm25_30" TEXT,
    "waktu_masuk" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "pm25datas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "@co2s" (
    "id" SERIAL NOT NULL,
    "co2_1" TEXT,
    "temp1" TEXT,
    "hum1" TEXT,
    "pres1" TEXT,
    "co2_2" TEXT,
    "temp2" TEXT,
    "hum2" TEXT,
    "pres2" TEXT,
    "co2_3" TEXT,
    "temp3" TEXT,
    "hum3" TEXT,
    "pres3" TEXT,
    "co2_4" TEXT,
    "temp4" TEXT,
    "hum4" TEXT,
    "pres4" TEXT,
    "co2_5" TEXT,
    "temp5" TEXT,
    "hum5" TEXT,
    "pres5" TEXT,
    "co2_6" TEXT,
    "temp6" TEXT,
    "hum6" TEXT,
    "pres6" TEXT,
    "co2_7" TEXT,
    "temp7" TEXT,
    "hum7" TEXT,
    "pres7" TEXT,
    "co2_8" TEXT,
    "temp8" TEXT,
    "hum8" TEXT,
    "pres8" TEXT,
    "co2_9" TEXT,
    "temp9" TEXT,
    "hum9" TEXT,
    "pres9" TEXT,
    "co2_0" TEXT,
    "temp0" TEXT,
    "hum0" TEXT,
    "pres0" TEXT,
    "waktu_masuk" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "@co2s_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "no2datas" (
    "id" SERIAL NOT NULL,
    "no2_1" TEXT,
    "no2_2" TEXT,
    "no2_3" TEXT,
    "no2_4" TEXT,
    "no2_5" TEXT,
    "no2_6" TEXT,
    "no2_7" TEXT,
    "no2_8" TEXT,
    "no2_9" TEXT,
    "no2_10" TEXT,
    "no2_11" TEXT,
    "no2_12" TEXT,
    "no2_13" TEXT,
    "no2_14" TEXT,
    "no2_15" TEXT,
    "no2_16" TEXT,
    "no2_17" TEXT,
    "no2_18" TEXT,
    "no2_19" TEXT,
    "no2_20" TEXT,
    "no2_21" TEXT,
    "no2_22" TEXT,
    "no2_23" TEXT,
    "no2_24" TEXT,
    "no2_25" TEXT,
    "no2_26" TEXT,
    "no2_27" TEXT,
    "no2_28" TEXT,
    "no2_29" TEXT,
    "no2_30" TEXT,
    "waktu_masuk" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "no2datas_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "shts" (
    "id" SERIAL NOT NULL,
    "suhu" TEXT,
    "temperature" TEXT,
    "waktu_masuk" TEXT,

    CONSTRAINT "shts_pkey" PRIMARY KEY ("id")
);
